nome = str(input('Digite seu nome: ')).strip()
print('Analisando seu nome...')
print('Maiúscula: {}'.format(nome.upper()))
print('Minúscula: {}'.format(nome.lower()))
print('Quantidade de letras sem espaços: {}'.format(len(nome.replace(' ',''))))
print('Quantidade de letras sem espaços: {}'.format(len(nome) - nome.count(' ')))
print('Primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Primeiro nome é {} e tem {} letras'.format(separa[0],len(separa[0])))
